version: "3.9"

services:
  identity_db:
    container_name: identity_db
    image: mcr.microsoft.com/mssql/server:latest
    restart: always
    volumes:
        - ./ReadyGo.Data/Identity:/var/opt/mssql/data
    ports:
      - 5001:1433
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "HHHHhhhh1111"
    networks:
      - application
      
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
        - 5000:8080
    networks:
        - application
   
networks:
  application:
    driver: bridge